/**
 * DEMO CONTENT — clearly fictional placeholder data so every section can be previewed.
 * Replace it from the admin panel (or run `npm run setup -- --reset` to start over).
 */
import type { SiteSettings } from "@/lib/settings-def";

const lorem =
  "This is **demo text**. Replace it from the admin panel with your own story — what you built, why it mattered, and what you learned.";

export const DEMO_SETTINGS: Partial<SiteSettings> = {
  profile: {
    name: "Your Name",
    initials: "YN",
    logo: "",
    headline: "BS Data Science & Applications · IIT Madras",
    tagline: "Student developer crafting data-driven products and cinematic web experiences.",
    email: "hello@example.com",
    location: "India",
    avatar: "/demo/portrait-front.webp",
    resume: "/demo/sample-resume.pdf",
  },
  socials: {
    github: "https://github.com/",
    linkedin: "https://www.linkedin.com/",
    x: "",
    instagram: "https://www.instagram.com/",
    youtube: "",
    leetcode: "https://leetcode.com/",
    kaggle: "https://www.kaggle.com/",
    medium: "",
    website: "",
  },
  seo: {
    title: "Your Name — Portfolio",
    description: "Portfolio of Your Name, BS Data Science student at IIT Madras: projects, certifications, achievements and more.",
    keywords: ["portfolio", "IIT Madras", "data science", "developer"],
    ogImage: "/demo/og.png",
    indexable: false,
  },
  footer: { text: "Designed & built with curiosity.", showBuiltWith: true, showAdminLink: false },
};

type Seed = { key: string; type: string; title: string; subtitle: string; config?: Record<string, unknown>; items?: Record<string, unknown>[]; featured?: number[] };

export const DEMO_SECTIONS: Seed[] = [
  {
    key: "hero",
    type: "hero",
    title: "Home",
    subtitle: "",
    config: {
      greeting: "Hello, I'm",
      roles: ["Data Science Student", "Full-Stack Developer", "ML Explorer", "Problem Solver"],
      primaryCtaLabel: "Explore my work",
      primaryCtaHref: "#projects",
      showResumeButton: true,
      show3D: true,
      portraitImages: ["/demo/portrait-front.webp", "/demo/portrait-back.webp"],
      showScrollHint: true,
    },
  },
  {
    key: "about",
    type: "about",
    title: "About",
    subtitle: "The story so far",
    config: {
      heading: "Curious mind. Builder at heart.",
      bio: `I'm a student in the **IIT Madras BS programme** (demo bio). I love turning data into decisions and ideas into products people enjoy using.\n\nRight now I'm working through the Diploma level while building side projects in machine learning and web development.\n\n${lorem}`,
      photo: "/demo/portrait-front.webp",
      photos: ["/demo/gallery-2.webp", "/demo/gallery-3.webp"],
      facts: ["Based in India", "Online BS @ IIT Madras", "Open to internships"],
      interests: ["Machine learning", "UI design", "Open source", "Chess", "Photography"],
    },
    items: [
      { label: "Projects built", value: 12, suffix: "+" },
      { label: "Certificates", value: 8, suffix: "" },
      { label: "Hackathons", value: 4, suffix: "" },
      { label: "Cups of chai", value: 999, suffix: "+" },
    ],
  },
  {
    key: "education",
    type: "education",
    title: "Education",
    subtitle: "Learning path — past, present and next",
    items: [
      {
        institution: "Indian Institute of Technology Madras",
        degree: "BS in Data Science and Applications",
        field: "Degree level",
        status: "upcoming",
        startDate: "2027-01",
        endDate: "2028-12",
        location: "Online · Chennai",
        logo: "/demo/logo-1.webp",
        description: "Planned next stage of the programme (demo entry).",
        courses: ["Deep Learning", "Big Data", "Software Engineering"],
      },
      {
        institution: "Indian Institute of Technology Madras",
        degree: "Diploma in Programming & Data Science",
        field: "Diploma level",
        status: "ongoing",
        startDate: "2025-09",
        endDate: "2026-12",
        grade: "CGPA 8.x (demo)",
        location: "Online · Chennai",
        logo: "/demo/logo-2.webp",
        description: "Currently pursuing. " + lorem,
        courses: ["Machine Learning Foundations", "DBMS", "App Development", "Java"],
      },
      {
        institution: "Indian Institute of Technology Madras",
        degree: "Foundation Level",
        field: "Data Science",
        status: "completed",
        startDate: "2024-05",
        endDate: "2025-08",
        grade: "Demo grade",
        logo: "/demo/logo-1.webp",
        courses: ["Python", "Statistics", "Mathematics", "Computational Thinking"],
      },
      {
        institution: "Demo Senior Secondary School",
        degree: "Class XII — Science (PCM)",
        status: "completed",
        startDate: "2022-04",
        endDate: "2024-03",
        grade: "9x% (demo)",
        logo: "/demo/logo-3.webp",
      },
    ],
  },
  {
    key: "skills",
    type: "skills",
    title: "Skills",
    subtitle: "Tools I use to turn ideas into reality",
    config: { showSphere: true, showBars: true },
    items: [
      { name: "Python", category: "Programming", level: 88, icon: "🐍", years: 3 },
      { name: "JavaScript", category: "Programming", level: 78, icon: "JS", years: 2 },
      { name: "TypeScript", category: "Programming", level: 70, icon: "TS", years: 1 },
      { name: "Java", category: "Programming", level: 60, icon: "☕", years: 1 },
      { name: "SQL", category: "Data", level: 80, icon: "🗄️", years: 2 },
      { name: "Pandas", category: "Data", level: 85, icon: "🐼", years: 2 },
      { name: "NumPy", category: "Data", level: 80, icon: "🔢", years: 2 },
      { name: "Scikit-learn", category: "Machine Learning", level: 72, icon: "🤖", years: 1 },
      { name: "PyTorch", category: "Machine Learning", level: 55, icon: "🔥", years: 1 },
      { name: "Statistics", category: "Machine Learning", level: 75, icon: "📊", years: 2 },
      { name: "React", category: "Web", level: 75, icon: "⚛️", years: 2 },
      { name: "Next.js", category: "Web", level: 68, icon: "▲", years: 1 },
      { name: "Tailwind CSS", category: "Web", level: 80, icon: "🎨", years: 2 },
      { name: "Flask", category: "Web", level: 65, icon: "🧪", years: 1 },
      { name: "Git", category: "Tools", level: 82, icon: "🌿", years: 3 },
      { name: "Figma", category: "Tools", level: 60, icon: "🖌️", years: 1 },
      { name: "Linux", category: "Tools", level: 65, icon: "🐧", years: 2 },
      { name: "Docker", category: "Tools", level: 45, icon: "🐳", years: 1 },
    ],
  },
  {
    key: "projects",
    type: "projects",
    title: "Projects",
    subtitle: "Selected work — click any project for the full story",
    config: { showFilters: true, showSearch: true, initialCount: 6 },
    featured: [0, 1],
    items: [
      { title: "Neural Notes", summary: "AI study assistant that turns lecture PDFs into flashcards and quizzes.", status: "completed", category: "Machine Learning", cover: "/demo/project-1.webp", gallery: ["/demo/project-2.webp", "/demo/project-3.webp"], tech: ["Python", "PyTorch", "FastAPI", "React"], role: "Solo developer", startDate: "2025-06", endDate: "2025-09", repoUrl: "https://github.com/", liveUrl: "https://example.com/", description: `## The problem\n${lorem}\n\n## What I built\n- PDF parsing pipeline\n- Question generation model\n- Spaced-repetition scheduler\n\n## Results\nDemo numbers: 200+ students used it during exams.` },
      { title: "Campus Connect", summary: "A community platform for online-degree students to find study groups.", status: "completed", category: "Web", cover: "/demo/project-2.webp", gallery: ["/demo/project-5.webp"], tech: ["Next.js", "TypeScript", "PostgreSQL", "Tailwind"], role: "Full-stack developer", startDate: "2025-01", endDate: "2025-04", repoUrl: "https://github.com/", description: `## Overview\n${lorem}` },
      { title: "StockSense", summary: "Interactive dashboard forecasting stock trends with time-series models.", status: "completed", category: "Data", cover: "/demo/project-3.webp", tech: ["Python", "Pandas", "Prophet", "Streamlit"], role: "Data analyst", startDate: "2024-10", endDate: "2024-12", repoUrl: "https://github.com/", description: lorem },
      { title: "PixelForge", summary: "Browser-based generative art tool built with WebGL shaders.", status: "in-progress", category: "Web", cover: "/demo/project-4.webp", tech: ["Three.js", "GLSL", "React"], role: "Creator", startDate: "2026-02", description: lorem },
      { title: "EcoTrack", summary: "Carbon-footprint tracker app with gamified weekly challenges.", status: "completed", category: "Mobile", cover: "/demo/project-5.webp", tech: ["Flutter", "Firebase"], role: "Team lead (4 members)", startDate: "2024-07", endDate: "2024-09", liveUrl: "https://example.com/", description: lorem },
      { title: "Quantum Quiz", summary: "Real-time multiplayer quiz game for classrooms.", status: "completed", category: "Web", cover: "/demo/project-6.webp", tech: ["Node.js", "Socket.io", "Vue"], role: "Backend developer", startDate: "2024-03", endDate: "2024-05", description: lorem },
      { title: "VoiceBridge", summary: "Speech-to-sign-language translator for accessibility (planned).", status: "planned", category: "Machine Learning", cover: "/demo/project-7.webp", tech: ["Python", "MediaPipe", "Transformers"], description: "A future project idea. " + lorem },
      { title: "OrbitOS", summary: "Personal productivity OS with AI scheduling (planned).", status: "planned", category: "Web", cover: "/demo/project-8.webp", tech: ["Next.js", "LLM APIs"], description: "A future project idea. " + lorem },
    ],
  },
  {
    key: "experience",
    type: "experience",
    title: "Experience",
    subtitle: "Internships, clubs & leadership",
    items: [
      { role: "Data Science Intern (demo)", organization: "Example Analytics Pvt Ltd", kind: "internship", startDate: "2026-05", endDate: "2026-07", location: "Remote", logo: "/demo/logo-4.webp", description: "- Built dashboards for KPI tracking\n- Automated weekly reports with Python\n- " + "Demo bullet point", skills: ["Python", "SQL", "Power BI"] },
      { role: "Web Team Coordinator", organization: "Demo Student Tech Club", kind: "club", startDate: "2025-08", location: "Online", logo: "/demo/logo-6.webp", description: "Leading a team of 6 building the club website and event portals.", skills: ["React", "Leadership"] },
      { role: "Volunteer Teacher", organization: "Sample NGO", kind: "volunteer", startDate: "2024-06", endDate: "2025-03", logo: "/demo/logo-5.webp", description: "Taught basic coding to school students on weekends.", skills: ["Teaching", "Scratch"] },
    ],
  },
  {
    key: "certifications",
    type: "certifications",
    title: "Certifications",
    subtitle: "Verified learning milestones",
    config: { showFilters: true },
    items: [
      { title: "Python for Data Science (sample)", issuer: "Demo Academy", issueDate: "2025-03", credentialId: "DEMO-001", credentialUrl: "https://example.com/", image: "/demo/cert-1.webp", file: "/demo/sample-certificate.pdf", skills: ["Python", "Pandas"] },
      { title: "Machine Learning Foundations (sample)", issuer: "Sample University", issueDate: "2025-07", credentialId: "DEMO-002", image: "/demo/cert-2.webp", skills: ["ML"] },
      { title: "Web Development Bootcamp (sample)", issuer: "Placeholder Institute", issueDate: "2024-11", image: "/demo/cert-3.webp", skills: ["HTML", "CSS", "JavaScript"] },
      { title: "Statistics Essentials (sample)", issuer: "Example Online", issueDate: "2024-08", image: "/demo/cert-4.webp", skills: ["Statistics"] },
    ],
  },
  {
    key: "achievements",
    type: "achievements",
    title: "Achievements",
    subtitle: "Moments I'm proud of",
    config: { horizontalReel: true },
    items: [
      { title: "Winner — Demo Hackathon 2025", organization: "Sample Tech Fest", date: "2025-02", category: "Hackathon", description: "Built an AI triage tool in 36 hours.", image: "/demo/achievement-1.webp" },
      { title: "Top 5% — Online Data Challenge", organization: "Example Platform", date: "2025-06", category: "Competition", description: "Ranked in the top 5% among 3,000 participants (demo).", image: "/demo/achievement-2.webp" },
      { title: "National Finalist — Ideathon", organization: "Demo Foundation", date: "2024-12", category: "Innovation", description: "Pitched a sustainability product to a jury.", image: "/demo/achievement-3.webp" },
      { title: "Gold — Inter-school Science Olympiad", organization: "Sample Board", date: "2023-11", category: "Academic", description: "Demo achievement description.", image: "/demo/achievement-4.webp" },
      { title: "100+ problems solved", organization: "LeetCode", date: "2026-01", category: "Coding", description: "Consistent practice in DSA (demo).", image: "/demo/achievement-5.webp" },
    ],
  },
  {
    key: "gallery",
    type: "gallery",
    title: "Gallery",
    subtitle: "Life beyond the code — drag to spin",
    config: { layout: "ring" },
    items: Array.from({ length: 8 }, (_, i) => ({ image: `/demo/gallery-${i + 1}.webp`, caption: `Demo moment ${i + 1}`, album: i < 4 ? "Events" : "Travel", date: `2025-0${(i % 9) + 1}` })),
  },
  {
    key: "roadmap",
    type: "roadmap",
    title: "Coming Soon",
    subtitle: "Upcoming education, projects and goals",
    items: [
      { title: "Complete the BS Degree level", kind: "education", targetDate: "2028-12", status: "planned", progress: 0, description: "Finish the full BS programme at IIT Madras." },
      { title: "Launch VoiceBridge beta", kind: "project", targetDate: "2026-12", status: "in-progress", progress: 35, description: "Accessibility-first translation tool." },
      { title: "Learn MLOps & cloud deployment", kind: "skill", targetDate: "2027-03", status: "in-progress", progress: 20, description: "Docker, CI/CD, model serving." },
      { title: "Summer research internship", kind: "career", targetDate: "2027-05", status: "planned", progress: 0, description: "Apply to research labs." },
    ],
  },
  {
    key: "testimonials",
    type: "testimonials",
    title: "Kind Words",
    subtitle: "What mentors & teammates say",
    items: [
      { name: "Demo Mentor", role: "Project mentor", quote: "A quick learner who ships polished work and asks the right questions. (Demo quote.)", avatar: "/demo/avatar-1.webp" },
      { name: "Sample Teammate", role: "Hackathon teammate", quote: "Calm under pressure and great at turning messy ideas into a working product. (Demo quote.)", avatar: "/demo/avatar-2.webp" },
      { name: "Example Professor", role: "Course instructor", quote: "Consistently thoughtful submissions with clear explanations. (Demo quote.)", avatar: "/demo/avatar-3.webp" },
    ],
  },
  {
    key: "blog",
    type: "blog",
    title: "Writing",
    subtitle: "Notes on things I'm learning",
    items: [
      { title: "How I study for IITM BS quizzes", excerpt: "A demo article excerpt about study systems and spaced repetition.", url: "https://example.com/", date: "2026-04", cover: "/demo/blog-1.webp", tags: ["Study", "IITM"] },
      { title: "My first ML model in production", excerpt: "Lessons learned from deploying a small model (demo).", url: "https://example.com/", date: "2026-02", cover: "/demo/blog-2.webp", tags: ["ML", "Deployment"] },
      { title: "Designing cinematic websites", excerpt: "Notes on motion, depth and restraint (demo).", url: "https://example.com/", date: "2025-12", cover: "/demo/blog-3.webp", tags: ["Design", "3D"] },
    ],
  },
  {
    key: "contact",
    type: "contact",
    title: "Contact",
    subtitle: "Let's talk",
    config: {
      heading: "Let's build something remarkable.",
      text: "Have an internship, project or collaboration in mind? Send a message — it lands straight in my inbox.",
      showForm: true,
      showEmail: true,
      availability: "Open to internships · 2027",
    },
  },
];
