/**
 * One-command setup:  npm run setup            (create DB, demo content, admin account)
 *                     npm run setup -- --reset (wipe content & re-seed demo data; keeps admin + uploads)
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { config as loadEnv } from "dotenv";

const root = process.cwd();
const envLocal = path.join(root, ".env.local");

function randomPassword() {
  // readable but strong: 4 groups, mixed case + digits
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";
  const pick = () => Array.from(crypto.randomBytes(5), (b) => chars[b % chars.length]).join("");
  return `${pick()}-${pick()}-${pick()}-Az7`;
}

if (!fs.existsSync(envLocal)) {
  const pw = randomPassword();
  const content = [
    "# Generated by `npm run setup` — keep this file private (it is git-ignored).",
    "DATABASE_URL=file:./data/portfolio.db",
    "DATABASE_AUTH_TOKEN=",
    `AUTH_SECRET=${crypto.randomBytes(48).toString("base64url")}`,
    "ADMIN_EMAIL=admin@example.com",
    `ADMIN_PASSWORD=${pw}`,
    "BLOB_READ_WRITE_TOKEN=",
    "SITE_URL=http://localhost:3000",
    "",
  ].join("\n");
  fs.writeFileSync(envLocal, content, { mode: 0o600 });
  console.log("✔ Created .env.local with a random AUTH_SECRET and admin password");
}
loadEnv({ path: envLocal, quiet: true });
loadEnv({ path: path.join(root, ".env"), quiet: true });
fs.mkdirSync(path.join(root, "data"), { recursive: true });

async function main() {
  const { db, schema, ensureSchema } = await import("../src/db/index");
  const { DEMO_SECTIONS, DEMO_SETTINGS } = await import("../src/db/seed-data");
  const { getSectionType } = await import("../src/lib/registry");
  const { passwordSchema } = await import("../src/lib/validation");
  const bcrypt = (await import("bcryptjs")).default;

  await ensureSchema();
  console.log("✔ Database schema ready");

  const reset = process.argv.includes("--reset");
  if (reset) {
    await db.delete(schema.items);
    await db.delete(schema.sections);
    await db.delete(schema.settings);
    console.log("✔ Cleared sections, items and settings");
  }

  const existing = await db.select().from(schema.sections);
  if (existing.length === 0) {
    const t = Date.now();
    let order = 0;
    for (const s of DEMO_SECTIONS) {
      const def = getSectionType(s.type)!;
      await db.insert(schema.sections).values({
        key: s.key,
        type: s.type,
        title: s.title,
        subtitle: s.subtitle,
        enabled: true,
        showInNav: s.type !== "hero",
        sortOrder: order++,
        config: JSON.stringify({ ...def.defaultConfig, ...(s.config ?? {}) }),
        updatedAt: t,
      });
      let i = 0;
      for (const data of s.items ?? []) {
        await db.insert(schema.items).values({
          id: crypto.randomUUID(),
          sectionKey: s.key,
          data: JSON.stringify(data),
          visible: true,
          featured: (s.featured ?? []).includes(i),
          sortOrder: i++,
          createdAt: t + i,
          updatedAt: t + i,
        });
      }
    }
    for (const [k, v] of Object.entries(DEMO_SETTINGS)) {
      await db.insert(schema.settings).values({ key: k, value: JSON.stringify(v), updatedAt: t }).onConflictDoNothing();
    }
    console.log(`✔ Seeded ${DEMO_SECTIONS.length} demo sections`);
  } else {
    console.log("• Content already exists — skipped demo seed (use --reset to re-seed)");
  }

  const users = await db.select().from(schema.users);
  if (users.length === 0) {
    const email = (process.env.ADMIN_EMAIL || "admin@example.com").toLowerCase().trim();
    const password = process.env.ADMIN_PASSWORD || "";
    const check = passwordSchema.safeParse(password);
    if (!check.success) {
      console.error("✖ ADMIN_PASSWORD is missing or too weak:", check.error.issues[0]?.message);
      process.exit(1);
    }
    await db.insert(schema.users).values({
      id: crypto.randomUUID(),
      email,
      name: "Admin",
      passwordHash: await bcrypt.hash(password, 12),
      createdAt: Date.now(),
    });
    console.log("\n──────────────────────────────────────────────");
    console.log("  Admin account created");
    console.log(`  Login:    http://localhost:3000/admin/login`);
    console.log(`  Email:    ${email}`);
    console.log(`  Password: ${password}`);
    console.log("  (stored in .env.local — change it after first login)");
    console.log("──────────────────────────────────────────────\n");
  } else {
    console.log("• Admin account already exists");
  }
  console.log("Done. Start the site with:  npm run dev");
}

main().catch((e) => {
  console.error("Setup failed:", e);
  process.exit(1);
});
